name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          palette: |
            {
              "background": "#0d1117",
              "snake": ["#FFA308"],
              "grass": ["#161b22", "#0e4429", "#006d32", "#26a641", "#39d353"]
            }
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          palette: |
            {
              "background": "#ffffff",
              "snake": ["#FFA308"],
              "grass": ["#ebedf0", "#9be9a8", "#40c463", "#30a14e", "#216e39"]
            }
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
